### ISSUE TITLE
TabItem title is not showing

### ISSUE THREAD

**Issue by iosapp3** [eshwavin/SETabView#1]
TabItem title is not showing in tabbar
import UIKit
import SETabView

class FourthViewController: UIViewController {
    
    var seTabBarItem: UITabBarItem! {
        return UITabBarItem(title: "Fourth", image: UIImage(named: "fourth"), tag: 0)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
       
        // Do any additional setup after loading the view.
    }

**Comment by eshwavin** [comment]
@iosapp3 We are working to provide support for title which will be there in the next release. Leaving the issue open and will close once the next version is out with the support.

**Comment by eshwavin** [comment]
The next version should be released by the weekend

**Comment by eshwavin** [comment]
On further deliberation, we feel like the design works best without titles. Hence we will not be adding it in the near future
