### ISSUE TITLE
When tabbar is hidden, still remains space

### ISSUE THREAD

**Issue by kkarakamis** [eshwavin/SETabView#2]
When applying 

 ```
   if let tabBar = self.parent?.parent as? AppTabBarController {
      tabBar.hideTabBars()
    }
```

tabbar hides itself but space still remains.

AppTabbarController is my tabbar controller which extends SETabViewController.

**Comment by eshwavin** [comment]
There is no function `hideTabBars()` in `SETabViewController`. This function should have been implemented by you. In case you are looking for support to show/hide the tab bar, we will look into it
